app/urls.py
from django.urls import path

from .views import home_view, profile_view, user_view, status_view, logout_view, fallen_view, fighting_view

urlpatterns = [
    path('', home_view),
    path('profile', profile_view),
    path('soldier', user_view),
    path('status', status_view),
    path('logout', logout_view),
    path('fallen', fallen_view),
    path('fighting', fighting_view)
]

nn19/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models

from django.utils import timezone

from django.contrib.auth.models import User

# Create your models here.
class CheckIn(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=2)
    datetime = models.DateTimeField()

    def __str__(self):
        return self.owner.username + ": " + self.status

class Soldier(models.Model):
    RANK_CHOICES = (
        ('unset', '--Unset--'),
        ('private', 'Private'),
        ('private_fc', 'Private First Class'),
        ('lance_c', 'Lance Corporal'),
        ('nut_c', 'Nut Corporal'),
        ('sergeant', 'Sergeant'),
        ('s_sergeant', 'Staff Sergeant'),
        ('n_sergeant', 'Nut Sergeant'),
        ('m_sergeant', 'Master Sergeant'),
        ('lieutenant', 'Lieutenant'),
        ('captain', 'Captain'),
        ('major', 'Major'),
        ('colonel', 'Colonel'),
        ('general', 'General'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rank = models.CharField(max_length=10, choices=RANK_CHOICES, default="unset")

    def __str__(self):
        return self.user.username

    def __text_color__(self, c):
        h = c.lstrip('#')
        t = tuple(int(h[i:i+2], 16) for i in (0, 2 ,4))
        l = (0.299*t[0] + 0.587*t[1] + 0.114*t[2])/255
        if l < 0.5:
            return "#FFFFFF"
        else:
            return "#000000"

    def get_color(self):
        color = "#000000"
        if self.rank == 'unset':
            color = "#000000"
        elif self.rank == 'private':
            color = "#FF0000"
        elif self.rank == "private_fc":
            color = "#FFA500"
        elif self.rank == "lance_c":
            color = "#FFFF00"
        elif self.rank == "nut_c":
            color = "#8B4513"
        elif self.rank == "sergeant":
            color = "#00BFFF"
        elif self.rank == "s_sergeant":
            color = "#0000FF"
        elif self.rank == "n_sergeant":
            color = "#191970"
        elif self.rank == "m_sergeant":
            color = "#8FBC8F"
        elif self.rank == "lieutenant":
            color = "#32CD32"
        elif self.rank == "captain":
            color = "#008000"
        elif self.rank == "major":
            color = "#6B8E23"
        elif self.rank == "colonel":
            color = "#556B2F"
        elif self.rank == "general":
            color = "#BDB76B"
        return (color, self.__text_color__(color))

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>NoNut19</title>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    {% block extrahead %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">NoNut19</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            NN19 Statistics
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/status">General Statistics</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/fighting">Fighting Soldiers</a>
                            <a class="dropdown-item" href="/fallen">Fallen Soldiers</a>
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Log out {{ user.username }}</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="form-inline my-2 my-lg-0" method="GET" action="/soldier">
                    <input class="form-control mr-sm-2" type="search" name="username" placeholder="Username" aria-label="Check user">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Check user</button>
                </form>
            </div>        
        </div>
    </nav>

    <div class="container py-5 py-md-4">
        {% block content %}
        {% endblock %}        
    </div>

    {% block extrabody %}
    {% endblock %}
</body>
</html>

app/templates/app/fallen.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="mb-4 mb-sm-3">NN19 Statistics</h1>

<ul class="nav nav-tabs mb-4 mb-sm-3">
    <li class="nav-item">
        <a class="nav-link" href="/status">General</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/fighting">Fighting</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="/fallen">Fallen</a>
    </li>
</ul>

<h3>Fallen Soldiers</h3>
{% if users %}
<ul class="list-group">
    {% for n in users %}
    <a href="/soldier?username={{ n.username|urlencode }}" class="list-group-item list-group-item-action">{{ n.username }}</a>
    {% endfor %}
</ul>
{% else %}
<p class="alert alert-success">No fallen soldiers yet! Keep on fighting!</p>
{% endif %}
{% endblock %}

app/templates/app/fighting.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="mb-4 mb-sm-3">NN19 Statistics</h1>

<ul class="nav nav-tabs mb-4 mb-sm-3">
    <li class="nav-item">
        <a class="nav-link" href="/status">General</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="/fighting">Fighting</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/fallen">Fallen</a>
    </li>
</ul>

<h3>Fighting Soldiers</h3>
{% if users %}
<ul class="list-group">
    {% for n in users %}
    <a href="/soldier?username={{ n.username|urlencode }}" class="list-group-item list-group-item-action">{{ n.username }}</a>
    {% endfor %}
</ul>
{% else %}
<p class="alert alert-danger">This is a sad moment in history. All soldiers have lost the war.</p>
{% endif %}
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
    <h1 class="mb-4 mb-sm-3">Log-in</h1>
    {% if login_error %}
    <p class="alert alert-danger">{{ login_error }}</p>
    {% endif %}
    <form class="mb-5 mb-sm-4" method="POST">
        <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" name="username" placeholder="Enter username">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" name="password" placeholder="Enter password">
        </div>
        {% csrf_token %}
        <button type="submit" name="login" class="btn btn-primary">Log in</button>
    </form>

    <h1 class="mb-4 mb-sm-3">Enlist</h1>
    {% if regsitration_error %}
    <p class="alert alert-danger">{{ registration_error }}</p>
    {% endif %}
    <form method="POST">
        <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" name="username" placeholder="Enter username">
            <small class="form-text text-muted">I recommend you use your Reddit username so other users and more importantly the mods can easily check your status, but of course, it's up to you.</small>
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" name="password" placeholder="Enter password">
            <small class="form-text text-muted">Don't worry. Your password is encrypted, and nobody, not even the admins, can know your password even if they wanted to.</small>
        </div>
        <div class="form-group">
            <label>Password (confirm)</label>
            <input type="password" class="form-control" name="password2" placeholder="Enter password again">
        </div>
        {% csrf_token %}
        <button type="submit" name="register" class="btn btn-primary">Enlist</button>
    </form>

{% endblock %}

app/templates/app/profile.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="mb-4 mb-sm-3">Your status</h1>
<p class="mb-2 mb-sm-1">You are <b>{% if status.status == "OK" %} OK {% else %} Failed {% endif %}</b> (as of {{ status.datetime }})</p>
<p class="mb-4 mb-sm-2">Your current rank is {% if currentuser.soldier.rank %}{{ currentuser.soldier.get_rank_display }}{% else %}unset. I recommend you change it :){% endif %}</p>
{% if result %}
<p class="alert alert-success">{{ result }}</p>
{% endif %}
{% if canpost %}
<form method="POST" class="mb-3 mb-sm-2">
    {% csrf_token %}
    <button class="btn btn-lg btn-success" type="submit" name="ok">I'm still here!</button>
</form>
<form method="POST" class="mb-3 mb-sm-2" onsubmit="return confirm('This will permanently\nchange your status to FAILED.\n(at least until I personally edit\nyour account info manually internally)\n\nAre you really sure you failed?');">
    {% csrf_token %}
    <button class="btn btn-lg btn-danger" type="submit" name="fail">I failed!</button>
</form>
<form method="POST" class="mb-3 mb-sm-2">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleFormControlSelect1">Choose rank</label>
        <select class="form-control" id="exampleFormControlSelect1" name="newrank">
            <option value="unset">--Unset--</option>
            <option value="private">Private</option>
            <option value="private_fc">Private First Class</option>
            <option value="lance_c">Lance Corporal</option>
            <option value="nut_c">Nut Corporal</option>
            <option value="sergeant">Sergeant</option>
            <option value="s_sergeant">Staff Sergeant</option>
            <option value="n_sergeant">Nut Sergeant</option>
            <option value="m_sergeant">Master Sergeant</option>
            <option value="lieutenant">Lieutenant</option>
            <option value="captain">Captain</option>
            <option value="major">Major</option>
            <option value="colonel">Colonel</option>
            <option value="general">General</option>
        </select>
    </div>
    <button class="btn btn-lg btn-primary" type="submit" name="change_rank">Change rank</button>
</form>
{% else %}
<p class="alert alert-warning">You did your best in this battle. Good luck next time! *<i>salute</i>*</p>
{% endif %}
{% endblock %}

app/templates/app/soldier.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="mb-4 mb-sm-3">Check user status</h1>
{% if error %}
<p class="alert alert-danger">{{ error }}</p>
{% endif %}
<form class="mb-5 mb-sm-4" method="GET">
    <div class="form-group">
        <label>Username</label>
        <input type="text" class="form-control" name="username" placeholder="Enter username" value="{{ request.GET.username }}">
    </div>
    <button type="submit" class="btn btn-primary">Check</button>
</form>

{% if quser %}  
    <h3>About <span style="color: {{ quser.soldier.get_color.0 }};">{{ quser }}</span>{% if quser.soldier.rank %}<img src="static/app/{{ quser.soldier.rank }}.png" style="height: 64px;margin-left: 20px;">{% endif %}</h3>

    <table class="table mb-5 mb-sm-4">
        <tr>
            <th>Rank</th>
            <td>{% if currentuser.soldier.rank %}{{ currentuser.soldier.get_rank_display }}{% else %}Unset{% endif %}</td>
        </tr>                
        <tr>
            <th>Join date</th>
            <td>{{ quser.date_joined }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{% if status.0.status == "OK" %} OK {% else %} Failed {% endif %} (as of {{ status.0.datetime }})</td>
        </tr>
        <tr>
            <th>Days since registration</th>
            <td>{{ days_since_registration_days }} day{% if days_since_registration_days > 1%}s{% endif %}, {{ days_since_registration_hours }} hour{% if days_since_registration_hours > 1 %}s{% endif %}</td>
        </tr>
    </table>

    <h3>Check-In History</h3>
    <table class="table mb-5 mb-sm-4">
        {% for s in status %}
        <tr>
            <th>{{ s.datetime }}</th>
            <td>{% if s.status == "OK" %} OK {% else %} Failed {% endif %}</td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p class="alert alert-primary">Enter the username of the person you want to check.</p>
{% endif %}

{% endblock %}

app/templates/app/status.html
{% extends 'app/base.html' %}

{% block extrahead %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js" integrity="sha256-MZo5XY1Ah7Z2Aui4/alkfeiq3CopMdV/bbkc/Sh41+s=" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<h1 class="mb-4 mb-sm-3">NN19 Statistics</h1>

<ul class="nav nav-tabs mb-4 mb-sm-3">
    <li class="nav-item">
        <a class="nav-link active" href="/status">General</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/fighting">Fighting</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/fallen">Fallen</a>
    </li>
</ul>

<h3>Progress</h3>
<table class="table mb-5 mb-sm-4">
    <tr>
        <th>Current UTC (server reference) time:</th>
        <td>{{ servertime }}</td>
    </tr>
    <tr>
        <th>Days since January 1, 2019:</th>
        <td>{{ dayssince }} day{% if dayssince > 1 %}s{% endif %} and {{ dayssince_hours }} hour{% if dayssince_hours > 1 %}s{% endif %} ({{ dayspercent }}%)</td>
    </tr>
    <tr>
        <th>Days until January 1, 2020:</th>
        <td>{{ daysuntil }} day{% if daysuntil > 1 %}s{% endif %} and {{ daysuntil_hours }} hour{% if daysuntil_hours > 1 %}s{% endif %} ({{ dayspercent_remaining }}%)</td>    </tr>
</table>
<canvas class="mb-4 mb-sm-3" id="progresschart" width="300px"></canvas>

<h3>Chart Data</h3>
<h5>Daily chart (New per day)</h5>
<canvas class="mb-4 mb-sm-3" id="dailychart" width="100%"></canvas>

<h5>Accumulation chart (Total from the beginning)</h5>
<canvas class="mb-4 mb-sm-3" id="newchart" width="100%"></canvas>

<h3>Soldier Statistics</h3>
<table class="table mb-5 mb-sm-4">
    <tr>
        <th>Total enlisted soldiers:</th>
        <td>{{ registered }}</td>
    </tr>
    <tr>
        <th>Total fighting soldiers:</th>
        <td>{{ ongoing }} ({{ ongoing_percent }}%)</td>
    </tr>
    <tr>
        <th>Total fallen soldiers:</th>
        <td>{{ failed }} ({{ failed_percent }}%)</td>
    </tr>
    <tr>
        <th>Total NN19 successful soldiers:</th>
        <td>{{ success }} ({{ success_percent }}%)</td>
    </tr>
</table>

<canvas class="mb-4 mb-sm-3" id="percentchart" width="300px"></canvas>



<h3>Newly enlisted soldiers</h3>
<h5>Newly enlisted today</h5>
{% if newregister %}
<ul class="list-group">
    {% for n in newregister %}
    <a href="/soldier?username={{ n.username|urlencode }}" class="list-group-item list-group-item-action">{{ n.username }}</a>
    {% endfor %}
</ul>
{% else %}
<p class="alert alert-info">No new soldiers today.</p>
{% endif %}

<h5 class="mt-5 mt-sm-4">New fallen soldiers today</h5>
{% if newfail %}
<ul class="list-group">
    {% for n in newfail %}
    <a href="/soldier?username={{ n.owner.username|urlencode }}" class="list-group-item list-group-item-action">{{ n.owner.username }}</a>
    {% endfor %}
</ul>
{% else %}
<p class="alert alert-info">No fallen soldiers today! Good job!</p>
{% endif %}
</p>
{% endblock %}

{% block extrabody %}
<script>
var myPieChart2 = new Chart('progresschart', {
    type: 'doughnut',
    data: {
        datasets: [{
            data: [ {{ dayssince }}, {{ daysuntil }} ],
            backgroundColor: ['rgba(0, 255, 0, 0.4)', 'rgba(255, 0, 0, 0.4)'],
            borderColor: ['rgba(0, 255, 0, 1)', 'rgba(255, 0, 0, 1)'],
            borderWidth: 1
        }],
        labels: [
            'Days passed', 'Days until'
        ]
    }
});

var myChart = new Chart("newchart", {
    type: 'line',
    data: {
        labels: [{% for d in days %}'{{ d }}',{% endfor %}],
        datasets: [{
            label: 'Fallen',
            data: [{% for o in failed_day_c %}{{ o }},{% endfor %}],
            backgroundColor: 'rgba(255, 0, 0, 0.4)',
            borderColor: 'rgba(255, 0, 0, 1)',
            borderWidth: 1
        }, {
            label: 'Fighting',
            data: [{% for o in ongoing_day_c %}{{ o }},{% endfor %}],
            backgroundColor: 'rgba(0, 255, 0, 0.4)',
            borderColor: 'rgba(0, 255, 0, 1)',
            borderWidth: 1
        }, {
            label: 'Total soldiers',
            data: [{% for o in total_members_c %}{{ o }},{% endfor %}],
            backgroundColor: 'rgba(0, 0, 255, 0.4)',
            borderColor: 'rgba(0, 0, 255, 1)',
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

var myDailyChart = new Chart("dailychart", {
    type: 'line',
    data: {
        labels: [{% for d in days %}'{{ d }}',{% endfor %}],
        datasets: [{
            label: 'Fallen',
            data: [{% for o in failed_d %}{{ o }},{% endfor %}],
            backgroundColor: 'rgba(255, 0, 0, 0.4)',
            borderColor: 'rgba(255, 0, 0, 1)',
            borderWidth: 1
        }, {
            label: 'Fighting',
            data: [{% for o in ongoing_d %}{{ o }},{% endfor %}],
            backgroundColor: 'rgba(0, 255, 0, 0.4)',
            borderColor: 'rgba(0, 255, 0, 1)',
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

var myPieChart = new Chart('percentchart', {
    type: 'doughnut',
    data: {
        datasets: [{
            data: [ {{ ongoing }}, {{ failed }} ],
            backgroundColor: ['rgba(0, 255, 0, 0.4)', 'rgba(255, 0, 0, 0.4)'],
            borderColor: ['rgba(0, 255, 0, 1)', 'rgba(255, 0, 0, 1)'],
            borderWidth: 1
        }],
        labels: [
            'Fighting', 'Fallen'
        ]
    }
});
</script>
{% endblock %}